#!/usr/bin/expect

# easy tool by 'expect' to jump to points.

spawn node
expect ">"
send "var p = console.log;\r"
expect ">"

send ".load  ./bin/www\r"
#send ".load  ./u-folder-basic.js\r"

expect "ok start interact:"
interact
