// Generated by CoffeeScript 1.8.0
(function() {
  var What, w;

  What = (function() {
    What._class_var = 8;

    What.prototype.aa = 'i am aa';

    What.class_met = function() {
      console.log('in class met');
      return 'class method';
    };

    What.get_count = function() {
      return this._titles;
    };

    What.prototype.call_other = function() {
      console.log("call ok:");
      return this.ok();
    };

    What.prototype.ok = function() {
      return console.log(this.constructor._class_var);
    };

    function What(artist, title) {
      this.artist = artist;
      this.title = title;
      this.constructor._titles++;
      this.bb = 99;
    }

    return What;

  })();

  w = new What('this is who', 'the title is unknown');

  console.log(w.aa, w.bb);

}).call(this);
