// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, a, p, promise_to_a;

  p = console.log;

  Promise = require("bluebird");

  a = function(seconds, callback) {
    var mili;
    mili = seconds * 1000;
    p('in function a');
    return setTimeout(callback, mili);
  };

  promise_to_a = Promise.promisify(a);

  a(3, function() {
    return p('I am in the function of callbacked');
  });

  p('here ---');

  promise_to_a(2);

  p('finished? ---');

}).call(this);
