// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, a, b, p;

  p = console.log;

  Promise = require("bluebird");

  a = new Promise(function(resolve) {
    return resolve();
  });

  b = Promise.resolve('b');

  b.then(function(what) {
    p('in b');
    return p(what);
  });

}).call(this);
