// Generated by CoffeeScript 1.8.0
(function() {
  var a, b, i, p;

  p = console.log;

  a = [1, 2, 3, 4, 5];

  b = (function() {
    var _i, _len, _results;
    _results = [];
    for (_i = 0, _len = a.length; _i < _len; _i++) {
      i = a[_i];
      _results.push(i);
    }
    return _results;
  })();

  p(typeof b);

  p(b);

}).call(this);
