// Generated by CoffeeScript 1.8.0
(function() {
  var jade, jr, p, str, t;

  jade = require("jade");

  str = "h the title\np the paragraph contents ...\ni end";

  t = jade.compile(str);

  p = console.log;

  jr = jade.render(str, {});

  p(jr);

}).call(this);
