// Generated by CoffeeScript 1.8.0
(function() {
  var Promise, bool, ep, p;

  p = console.log;

  Promise = require("bluebird");

  ep = Promise.resolve(true);

  bool = false;

  if (ep) {
    ep.then(function(what) {
      p("what: " + what);
      return bool = what;
    }).then(function(b) {
      return p("bool here: " + bool);
    });
  }

  p("bool : " + bool);

}).call(this);
