// Generated by CoffeeScript 1.8.0
(function() {
  var a, b, p;

  p = console.log;

  a = {
    a: 1,
    b: 2
  };

  b = {
    ba: 1,
    bb: 2
  };

  p(a);

  p("b : " + b + " ", b);

}).call(this);
