// Generated by CoffeeScript 1.8.0
(function() {
  var a, async, p, square, square_fun, square_things;

  async = require('async');

  p = console.log;

  a = [1, 2, 3, 4, 5];

  square = function(n) {
    return n * n;
  };

  square_fun = function(n) {
    var the_fun;
    the_fun = function(callback) {
      p('to square ', n);
      square(n);
      return callback(null, square(n));
    };
    return the_fun;
  };

  square_things = a.map(square_fun);

  p(square_things);

  async.series(square_things);

}).call(this);
