// Generated by CoffeeScript 1.8.0
(function() {
  var d, p, s, t;

  p = console.log;

  t = Date.now();

  s = ' ' + t;

  p(s);

  p('parseInt: ', parseInt(s));

  d = Date(s);

  p(d);

}).call(this);
